spring.application.name=examenes

server.port=8088

spring.datasource.url=jdbc:postgresql://ep-lucky-glitter-aqiyeekz-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_skbY58jNZvaq
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true